name: Deploy sls app

on: 
  push:
    branches:
      - main

jobs:     
  deploy:
    runs-on: ubuntu-latest
    env:
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
    - uses: actions/checkout@v3
    - name: install-python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'    
    - name: install serverless
      run: npm i -g serverless@3.38.0

    - name: Log in to Amazon ECR
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region $AWS_REGION
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin <905050315480>.dkr.ecr.$AWS_REGION.amazonaws.com
        aws ecr describe-repositories --repository-names aws-test || aws ecr create-repository --repository-name aws-test

    - name: Build, tag, and push Docker image
      env:
        ECR_REPOSITORY: <905050315480>.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/aws-test
      run: |
        docker build -t aws-test .
        docker tag aws-test:latest $ECR_REPOSITORY:latest
        docker push $ECR_REPOSITORY:latest
      
    - name: severless deploy
      run: sls deploy --verbose --force
